web:
  build: ./web
  ports:
    - "3000:3000"
  volumes:
    - ./code/web:/srv/www/
  command: node /srv/www/server.js
  links:
    - api
    - redis
    - mongodb

api:
  build: ./api
  ports:
    - "3030:3030"
  volumes:
    - ./code/api:/srv/www/
  command: bash -c "cd /srv/www && npm install && node /srv/www/server.js"

redis:
  image: redis

mongodb:
  image: tutum/mongodb
  ports:
    - "27017:27017"
  environment:
    MONGODB_PASS: password

